# below three lines: workaround prior to official 3.7 support: https://docs.travis-ci.com/user/languages/python/
dist: xenial
language: python
python: '3.7'

# for building docs
sudo: required
node_js:
  - "lts/*"

install:
- pip install -r requirements.txt

script: pytest tests

before_deploy:
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update && sudo apt-get install yarn
- yarn install --ignore-engines  # otherwise eslint sub package clashes with node
- yarn docs:build

deploy:
# for deploying to pypi
- provider: pypi
  on:
    branch: master  # only build on master branch
    tags: true  # only build for tagged pushes
  user: shongololo
  # ran into issues - per support recommendations, run against travis-ci.com instead of travis-ci.org
  # travis encrypt <<password>> --com --debug
  password:  # travis encrypt your-password-here
    secure: O6mZQ/okx4v/8UyfIvfg5GFVrEgw4AAwSLeKM0UG/LJYipttbBKyIN8gGzhxz/C8Wk5pcf7AD4Rbasa/9AZB8Lv8eok2sWx7j07B1EyL0p55AhZC1mQg68riM5R6IQsPiP2HhWXh2ifhFclQnTGOVhzW2NSsPg6+We4r8BsxqpqNPkVIeEWZfb2ynJmPQ0sUXG4MMUMas9h2TY7IxQawR2vsplP+7PE2SyNQUVIAces8NzoGTORdFP5n35xf6bDcb5gWcKhx6+w7wcPL6vwPBP9MVhrO0+0N5mZBZqVdrsmi5SndF6LU8f1XDwzWRNxh7dvtnvABxyny2U6es5cCMoY0nSfLGlS4X3JC5fnufu5UEXJZ//OLTYmFfbHRfDOVcGJYdrYKo5FSUgRiA3Y4UBUw4JJAgtcWhhLO2CuRz1aiwlUMMOTakQ9kCsVpkm9uaPKnX1pVBCNMNsy+VaSIyWV+sHP6z08S06ul6Za3SB3GZ8nimk0DPn7u3CF68WVEG8pQPqmdVcx7MTXlJqKfvZJ5L/LouB862eEOe7GwwssYMjBUnkfL4+YIYscSg8nTQifoX9bJJiuMw1Tj/fksQlb99mz+tJqs5xEl2KBJBfaTUp2Ao2x3qF/245Ul3YT/hbo8elihocwXX3ENFMDg4R8dA+vPXrZaJYH8OM2NBEs=
  distributions: "sdist bdist_wheel"  # default is only sdist, so upload linux wheel as well
  skip_existing: true
  # skip_upload_docs: true  # default
  # docs_dir: build/docs  # default
# for deploying docs
- provider: pages
  on:
    branch: master  # only build on master branch
  local-dir: docs/.vuepress/dist
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Generate personal token in github, then set in travis settings page as a secure variable
# - provider: releases  # github releases
#   api_key: $GITHUB_TOKEN
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     branch: master
#     tags: true
