language: python
sudo: required  # workaround prior to official 3.7 support
dist: xenial  # workaround prior to official 3.7 support
python: '3.7'
node_js:
  - "lts/*"

install:
- pip install -r requirements.txt

script: pytest

before_deploy:
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update && sudo apt-get install yarn
- yarn install --ignore-engines  # otherwise eslint sub package clashes with node
- yarn docs:build

deploy:
# for deploying to pypi
- provider: pypi
  on:
    branch: master  # only build on master branch
    tags: true  # only build for tagged pushes
  user: 'shongololo'
  password:  # travis encrypt your-password-here
    secure: "u/t6nfLiVp8ywBjXrtBjF1j5nz55ziguKIHdqWx3/EfnHIgAbpfKsS8EZY9rc4xHNTO7lIAjJTAYgzW1mENPx2BJEfro2zy38drmqVZ5eJn/K5RYU8S61JDmU659l+0xcvKJapQa4BFFF7IfBQTifx0s2t7iIjMBE7GOiB9garPM44N6MXNT6bVzcx5QNhLGhhm0J5al/Vbqv9Plu3NuMAHBgbjlBAfHSs5soubxbUVoG+eOVLfrdc+obuydIZ15jGYrI61G/PYOnfI1m6hHtdMJscp6oIRdi4ipe7lo+ug7ijVZ/8ctvWUWOk1W/pmmR9dnK3beoofM5cIyDMSWsrVd6+3RCvw3BHEt2RkujGiOGTjcNbR99C8zoZImqpkbUjSIPfaqMwLAOSYDa/ghyoZ/5ZB98lBBhL69BfnWy5UnxgUL+8dRX29ck51hDkuPoiqlF87xLtEMa/T30fvZJzuw4DSlEMqwnohpDvXOu22l6pXZuJDQceOHdfKhEc+iiI3aVjbTGjf5RMX3HEmZrIpTbPglf04in6KOI4nCYAmw2P3lpJFowerWh1ca/GaCz/klLJDx+Le0QcJEh4HJZbAoNZnVqCWzt/Ns0qnZJ8SkKeInp6NVtfk/9GgD+hZFzBIRdr/zKhNHWLYwuYnfO0TFBh+OI0b4Or7ffXP0pIU="
  distributions: "sdist bdist_wheel"  # default is only sdist, so upload linux wheel as well
# for deploying docs
- provider: pages
  on:
    branch: master  # only build on master branch
    tags: false  # only build for tagged pushes
  local-dir: docs/.vuepress/dist
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Generate personal token in github, then set in travis settings page as a secure variable
  keep-history: true
