language: python
sudo: required  # workaround prior to official 3.7 support
dist: xenial  # workaround prior to official 3.7 support
python: '3.7'

install:
- pip install -r requirements.txt

script: pytest

before_deploy:
- sphinx-build -b html ./docs/source ./docs

deploy:
# for deploying to pypi
- provider: pypi
  on:
    branch: master  # only build on master branch
    tags: true  # only build for tagged pushes
  user: 'shongololo'
  password:  # travis encrypt your-password-here
    secure: "Z6xABHSq1TD3qQCvQm3/VGLD/9bplKlQhbbDjER/3NEjY0uuztfP1iku4UB9jeoQKj19kn0YquyQ9ZBQxYTVPU1VjoztMu6punA0+5p+ZLL9s78Cm76J3OsQ21R412lZUS1/GMyLOD1VQcWOQCuKuMealt5eOtLNEPVZS85km76pTy9u3yzIpY7/a718XJaIyRNlkC11fS06gi8a0Y9iDr9GVSjGWs+rRyJn40Mm7gHedAfLD8ksYu3r5/sFkNsou4GQU/QNkHhafEMu/7gF48W3eKXI7do4QXqA/HigFvxG7tB53gtADP+jTN/LF6lgg3ekv0L+q3Z+b+6rkgtaTTdK9KouSFtbCUiiVxMfa/2TMNP5zxW9hWxDniAWvTLk8Ib+sYHm85nA/DCEMUWvXXiUeaJAhv2yoh2dZaGVx9PyR8ll02zyFC+HfVSGtz92DBNyZXuFApj9AXXxGSDy3Kt01YTGXW0vmhrzcALEF7M//SadZPuZFxO0xONpMg+XkQcsaXXVjv61ifJ6t62EZrukF39dyXQbdy3aMPjWo3i2/xhQiV0MJTOns7nr9YxXMGynLvy2VCkvXCTLy89y7JPMm7sMXZlkQdnkZCf9VpnyGzoq/lxQLHssE3Qosz+qu2hM9YMX9pxztfAKyE0/0Ja855GMYWi+rZS43afFqRc="
  distributions: "sdist bdist_wheel"  # default is only sdist, so upload linux wheel as well
# for deploying docs
- provider: pages
  on:
    branch: master  # only build on master branch
    tags: true  # only build for tagged pushes
  local-dir: docs
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Generate personal token in github, then set in travis settings page as a secure variable
  keep-history: true
