os:
  - linux
  - osx

language: python

python:
  - '3.6'

install:
  - pip install -r requirements.txt

script:
  - pytest
  - cd docs
  - make html
  - cd ..

deploy:
  provider: pypi
  user: 'shongololo'
  password:
    secure: 'Your encrypted password'
  on:
    tags: true
    branch: master
  distributions: 'sdist bdist_wheel' # default is only sdist